feat: Audit trpc calls
captableinc/captable pull request #440
Opened 2024-07-13 07:08 UTC by VK-RED

resolves #275

2024-07-17 09:09 UTC, dahal commented on src/server/audit/schema.ts
> +    "passkey.registrationOptions-created",
Please change both `authOptions... and registration...` to `passkey.updated`, details will be on summary

2024-07-17 09:11 UTC, dahal commented on src/trpc/routers/company-router/router.ts
> +            action: "company.lastAccessed",
I don't think we need this, let's remove it.

2024-07-17 09:12 UTC, dahal commented on src/server/audit/schema.ts
> +    "company.lastAccessed",
I don't think we need this, lets remove `lastAccessed` audit

2024-07-17 09:13 UTC, dahal commented on src/server/audit/schema.ts
>      "update.private-status",
While you are on this, can you please change these two status with `update.updated`, details will be on summary

2024-07-17 09:13 UTC, dahal requested changes
Great work on this PR @VK-RED , it looks good overall . Please make these recommended changes.

2024-07-17 09:37 UTC, VK-RED commented
Will update it soon @dahal !!

2024-07-20 05:04 UTC, dahal approved these changes

2024-07-20 05:04 UTC, merged